language: java
jdk:
- oraclejdk8

addons:
  ssh_known_hosts: github.com

before_install:
   # Get the deploy key by using Travis's stored variables to decrypt deploy_key.
  - openssl aes-256-cbc -K $encrypted_72f66166909e_key -iv $encrypted_72f66166909e_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - ulimit -s 1082768  # Require a bit of more memory.

after_success:
  - bash git_push.sh

 
