language: java
jdk:
- oraclejdk8

addons:
  ssh_known_hosts: github.com

before_install:
   # Get the deploy key by using Travis's stored variables to decrypt deploy_key.enc

before_deploy:
  - openssl aes-256-cbc aes-256-cbc -K $encrypted_f41f4efce4cd_key -iv $encrypted_f41f4efce4cd_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

after_success:
  - bash git_push.sh

 
